[project]
name = "srh-ai-ceo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "langgraph>=1.2.6",
    "loguru>=0.7.3",
    "openai>=2.43.0",
    "orjson>=3.11.9",
    "psycopg[binary]>=3.3.4",
    "rank-bm25>=0.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.6.0",
    "sqlalchemy>=2.0.51",
    "streamlit>=1.58.0",
    "watchdog>=6.0.0",
]
